SERVER_NAME = "localhost:5000"
SITE_URL = "http://" + SERVER_NAME
TESTING = True
NO_DOI_MINTING = True
USE_TWITTER = False
CFG_CONVERTER_URL = 'http://localhost:5500'
CFG_TMPDIR = '/Users/watt/tmp/hepdata/tmp'  # replace with a suitable existing local directory
CFG_DATADIR = '/Users/watt/tmp/hepdata/data'  # replace with a suitable existing local directory
MAIL_SERVER = '127.0.0.1'
MAIL_PORT = 1025
CELERY_BEAT_SCHEDULE = {}
# RUN_SELENIUM_LOCALLY = True
