SITE_URL = "http://localhost:5000"
TESTING = True
NO_DOI_MINTING = True
USE_TWITTER = False
CFG_CONVERTER_URL = 'http://localhost:5500'
CFG_TMPDIR = '/Users/watt/tmp/hepdata/tmp'  # replace with a suitable local directory
CFG_DATADIR = '/Users/watt/tmp/hepdata/data'  # replace with a suitable local directory
MAIL_SERVER = 'localhost'
CELERY_BEAT_SCHEDULE = {}
# RUN_SELENIUM_LOCALLY = True
# RATELIMIT_ENABLED = False
