SERVER_NAME = "localhost:5000"
SITE_URL = "http://" + SERVER_NAME
TESTING = True
NO_DOI_MINTING = True
USE_TWITTER = False
CFG_CONVERTER_URL = 'http://converter:5000'
CFG_TMPDIR = '/code/tmp'
CFG_DATADIR = '/code/tmp'
MAIL_SERVER = 'localhost'
CELERY_BROKER_URL = "redis://cache:6379/0"
CELERY_RESULT_BACKEND = "redis://cache:6379/1"
CACHE_REDIS_URL = "redis://cache:6379/0"
ACCOUNTS_SESSION_REDIS_URL = CACHE_REDIS_URL
TEST_DB_HOST = "db"
OPENSEARCH_HOST = "os"
SEARCH_HOSTS = [
    'os:9200'
]
CELERY_BEAT_SCHEDULE = {}
# RUN_SELENIUM_LOCALLY = True
